### ISSUE TITLE
Login failed "try again later with numbers"

### ISSUE THREAD

**Issue by ClashofJeann** [UltraPowaDev/UCS#33]
Hi, new issue with commits: 
   at UCS.Core.DatabaseManager.GetAccount(Int64 playerId) in C:\UCS-ucs-recode\V6\UCS-master\Ultrapowa Clash Server\Core\DatabaseManager.cs:line 132
20160427165941	[UCS]    An exception occured during GetAccount processing :System.NullReferenceException: Object reference not set to an instance of an object.
   at UCS.Logic.ClientAvatar.LoadFromJSON(String jsonString) in C:\UCS-ucs-recode\V6\UCS-master\Ultrapowa Clash Server\Logic\ClientAvatar.cs:line 366
   at UCS.Core.DatabaseManager.GetAccount(Int64 playerId) in C:\UCS-ucs-recode\V6\UCS-master\Ultrapowa Clash Server\Core\DatabaseManager.cs:line 132
System.NullReferenceException: Object reference not set to an instance of an object.
   at UCS.Logic.ClientAvatar.LoadFromJSON(String jsonString) in C:\UCS-ucs-recode\V6\UCS-master\Ultrapowa Clash Server\Logic\ClientAvatar.cs:line 366
   at UCS.Core.DatabaseManager.GetAccount(Int64 playerId) in C:\UCS-ucs-recode\V6\UCS-master\Ultrapowa Clash Server\Core\DatabaseManager.cs:line 132

Players can't login.
Problem with database? 
Thank you for reading that.

**Comment by smartclash** [comment]
Try to trucanate the database and then try again

**Comment by ClashofJeann** [comment]
Now no errors with db but with packet...Thank you for the help
